### PR TITLE
8.0 travis

### PR DESCRIPTION
**Pull request by kryskool**
Hi @alexis-via 

Before add new module monncard_expense, i enable tavis on 8.0 branch

I fix issue with pylint and flake8

It's seem original test in mooncard_invoice doesn't work correctly 

Regards,

### CODE REVIEW

**Comment by kryskool** [comment]
@alexis-via can you enable travis on this repo ?

**Comment by kryskool** [comment]
Thanks @alexis-via

**Comment by kryskool** [comment]
@alexis-via can you active this repo on travis at this address https://travis-ci.org/akretion/odoo-mooncard-connector

Regards

**Comment by alexis-via** [comment]
@kryskool Done. Thanks for the hint.

**Pull request merged**
